databases:
  - name: sms-db
    databaseName: sms
    user: sms_user
    plan: free

services:
  - type: web
    name: sms-web
    env: static
    rootDir: web
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: VITE_API_URL
        value: https://sms-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
